import type {
  Brand,
  Category,
  Client,
  Faq,
  Location,
  Product,
  Project,
} from "@/lib/types";
import { imageAsset } from "@/lib/utils";

export const categories: Category[] = [
  {
    slug: "office-interiors",
    name: "Office Interiors",
    summary: "Space planning, furniture selection and fit-out coordination for working offices.",
    description:
      "Office-interior enquiries are handled around actual site needs, furniture mix, workflow and finish preferences. Final drawings, dimensions and specifications are confirmed during consultation.",
    image: imageAsset("categories/office-interiors/cover.jpeg"),
    featured: true,
    displayOrder: 1,
    keywords: ["office interior solutions", "commercial furniture supplier"],
  },
  {
    slug: "office-furniture",
    name: "Office Furniture",
    summary: "Desks, seating, storage and collaborative furniture for modern workplaces.",
    description:
      "Destino helps teams select coordinated office furniture for cabins, workstations, meeting rooms and support areas, with product details finalized through quotation.",
    image: imageAsset("categories/office-furniture/cover.jpeg"),
    featured: true,
    displayOrder: 2,
    keywords: ["office furniture in Visakhapatnam", "office furniture in Bengaluru"],
  },
  {
    slug: "customized-furniture",
    name: "Customized Furniture",
    summary: "Made-to-fit furniture solutions for offices, institutions, homes and hospitality spaces.",
    description:
      "Customized furniture requests are scoped from room measurements, use case, material preference and design direction. Admin-managed records can later hold drawings and confirmed specifications.",
    image: imageAsset("categories/customized-furniture/cover.jpeg"),
    featured: true,
    displayOrder: 3,
    keywords: ["customized office furniture", "custom furniture design"],
  },
  {
    slug: "institutional-furniture",
    name: "Institutional Furniture",
    summary: "Furniture support for education, public and organizational environments.",
    description:
      "Institutional furniture enquiries can include seating, work tables, administrative furniture and project supply coordination across verified service locations.",
    image: imageAsset("categories/institutional-furniture/cover.jpeg"),
    displayOrder: 4,
    keywords: ["institutional furniture", "commercial furniture supplier"],
  },
  {
    slug: "domestic-furniture",
    name: "Domestic Furniture",
    summary: "Furniture and soft seating for residential and compact studio spaces.",
    description:
      "Domestic furniture enquiries are handled as guided selections or custom requirements. Pricing, finish and dimensions are confirmed only after the selected product is verified.",
    image: imageAsset("categories/domestic-furniture/cover.jpeg"),
    displayOrder: 5,
    keywords: ["domestic furniture", "customized furniture"],
  },
  {
    slug: "restaurant-furniture",
    name: "Restaurant Furniture",
    summary: "Durable seating and tables for cafes, dining rooms and quick-service spaces.",
    description:
      "Restaurant furniture selections are planned around circulation, service style, durability and finish requirements.",
    image: imageAsset("categories/restaurant-furniture/cover.jpeg"),
    featured: true,
    displayOrder: 6,
    keywords: ["restaurant furniture", "cafeteria furniture"],
  },
  {
    slug: "ergonomic-chairs",
    name: "Ergonomic Chairs",
    summary: "Task seating options for focused, all-day office work.",
    description:
      "Ergonomic-chair enquiries can be filtered by application, finish and partner brand. Exact adjustment options and dimensions are model-specific and confirmed during quotation.",
    image: imageAsset("categories/ergonomic-chairs/cover.jpeg"),
    featured: true,
    displayOrder: 7,
    keywords: ["ergonomic office chairs", "office chairs"],
  },
  {
    slug: "office-chairs",
    name: "Office Chairs",
    summary: "Task, executive, visitor and lounge seating for office environments.",
    description:
      "Office-chair selections can cover task chairs, meeting-room seating, visitor chairs and executive seating based on the buyer's workflow and finish preference.",
    image: imageAsset("categories/office-chairs/cover.jpeg"),
    displayOrder: 8,
    keywords: ["office chairs", "ergonomic office chairs"],
  },
  {
    slug: "office-tables",
    name: "Office Tables",
    summary: "Executive desks, meeting tables, work tables and storage-connected table systems.",
    description:
      "Office-table enquiries are matched to space, team size, cabling needs and finish preferences. Dimensions are confirmed after product or custom scope selection.",
    image: imageAsset("categories/office-tables/cover.jpeg"),
    displayOrder: 9,
    keywords: ["office tables and workstations", "office tables"],
  },
  {
    slug: "cafeteria-furniture",
    name: "Cafeteria Furniture",
    summary: "Tables and seating for canteens, office cafes and hospitality break-out areas.",
    description:
      "Cafeteria furniture is planned for ease of cleaning, circulation, seating capacity and usage intensity.",
    image: imageAsset("categories/cafeteria-furniture/cover.jpeg"),
    displayOrder: 10,
    keywords: ["cafeteria furniture", "restaurant furniture"],
  },
  {
    slug: "workstation-tables-and-chairs",
    name: "Workstation Tables and Chairs",
    summary: "Integrated workstation systems with coordinated tables, panels and task seating.",
    description:
      "Workstation furniture is scoped around floor plate, team workflows, privacy needs and electrical planning. Final module sizes are confirmed during design review.",
    image: imageAsset("categories/workstation-tables-and-chairs/cover.jpeg"),
    featured: true,
    displayOrder: 11,
    keywords: ["office tables and workstations", "workstation chairs"],
  },
];

export const brands: Brand[] = [
  {
    slug: "hof",
    name: "HOF",
    logo: imageAsset("brands/hof.jpg"),
    kind: "channel-partner",
    summary: "Channel partner for office seating and workspace furniture enquiries.",
    displayOrder: 1,
  },
  {
    slug: "spacewood",
    name: "Spacewood",
    logo: imageAsset("brands/spacewood.png"),
    kind: "channel-partner",
    summary: "Channel partner for modular furniture and workspace solutions.",
    displayOrder: 2,
  },
  {
    slug: "paradise",
    name: "Paradise Furniture",
    logo: imageAsset("brands/paradise.png"),
    kind: "channel-partner",
    summary: "Channel partner for seating and commercial furniture ranges.",
    displayOrder: 3,
  },
];

export const products: Product[] = [
  {
    slug: "ergonomic-task-chair-range",
    name: "Ergonomic Task Chair Range",
    categorySlug: "ergonomic-chairs",
    brandSlug: "hof",
    furnitureType: "Chairs",
    image: imageAsset("products/ergonomic-task-chair-range/cover.jpeg"),
    gallery: [
      imageAsset("products/ergonomic-task-chair-range/cover.jpeg"),
      imageAsset("products/ergonomic-task-chair-range/gallery-02.jpeg"),
    ],
    shortDescription:
      "A curated ergonomic-chair range for focused office work, available for model-specific quotation.",
    fullDescription:
      "Suitable for task seating, cabin seating and workstation deployments where posture support and coordinated finishes matter. Confirmed adjustment details, dimensions and finishes are added at quotation stage.",
    features: [
      "Guided model selection by usage and seat count",
      "Suitable for workstation and cabin environments",
      "Partner-brand options can be compared during consultation",
    ],
    relatedSlugs: ["workstation-table-system", "executive-office-chair-range"],
    featured: true,
    displayOrder: 1,
    status: "published",
    seoTitle: "Ergonomic Office Chairs | Destino Furniture Studio",
    seoDescription:
      "Explore ergonomic office chair ranges from Destino Furniture Studio for task seating, workstation seating and office projects.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "executive-office-chair-range",
    name: "Executive Office Chair Range",
    categorySlug: "office-chairs",
    brandSlug: "hof",
    furnitureType: "Chairs",
    image: imageAsset("products/executive-office-chair-range/cover.jpeg"),
    gallery: [
      imageAsset("products/executive-office-chair-range/cover.jpeg"),
      imageAsset("products/executive-office-chair-range/gallery-02.jpeg"),
    ],
    shortDescription:
      "Executive and manager seating options for cabins, reception suites and meeting rooms.",
    fullDescription:
      "Destino supports executive seating selection with finish, comfort and project-context guidance. Final upholstery, mechanism and dimensional details are confirmed against the chosen model.",
    features: [
      "Cabin and meeting-room seating applications",
      "Finish coordination with tables and storage",
      "Product-specific WhatsApp and quotation flow",
    ],
    relatedSlugs: ["office-desk-and-table-range", "lounge-and-visitor-seating"],
    featured: true,
    displayOrder: 2,
    status: "published",
    seoTitle: "Office Chairs for Workplaces | Destino Furniture Studio",
    seoDescription:
      "Request office chair quotations for cabins, meeting spaces and visitor seating from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "workstation-table-system",
    name: "Workstation Table System",
    categorySlug: "workstation-tables-and-chairs",
    brandSlug: "spacewood",
    furnitureType: "Workstations",
    image: imageAsset("products/workstation-table-system/cover.jpeg"),
    gallery: [
      imageAsset("products/workstation-table-system/cover.jpeg"),
      imageAsset("products/workstation-table-system/gallery-02.jpeg"),
      imageAsset("products/workstation-table-system/gallery-03.jpeg"),
    ],
    shortDescription:
      "Workstation tables and coordinated task seating for team offices and project rollouts.",
    fullDescription:
      "Workstation systems are planned around team size, circulation, storage and privacy needs. Exact module dimensions and finishes are confirmed after site measurement or layout review.",
    features: [
      "Linear and team-based planning support",
      "Coordinated chairs, panels and storage",
      "Suitable for office-interior and turnkey enquiries",
    ],
    relatedSlugs: ["ergonomic-task-chair-range", "office-interior-turnkey-furniture"],
    featured: true,
    displayOrder: 3,
    status: "published",
    seoTitle: "Workstation Tables and Chairs | Destino Furniture Studio",
    seoDescription:
      "Plan workstation tables and chairs for offices in Visakhapatnam, Kakinada and Bengaluru with Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "office-desk-and-table-range",
    name: "Office Desk and Table Range",
    categorySlug: "office-tables",
    brandSlug: "spacewood",
    furnitureType: "Tables",
    image: imageAsset("products/office-desk-and-table-range/cover.jpeg"),
    gallery: [
      imageAsset("products/office-desk-and-table-range/cover.jpeg"),
      imageAsset("products/office-desk-and-table-range/gallery-02.jpeg"),
    ],
    shortDescription:
      "Office tables for cabins, staff rooms, meeting areas and project workspaces.",
    fullDescription:
      "Destino assists buyers with desk and table selection based on room use, storage needs, finish coordination and installation context. Exact sizes are confirmed during quotation.",
    features: [
      "Cabin, meeting and staff-room applications",
      "Finish matching with storage and seating",
      "Custom dimensions available after scope review",
    ],
    relatedSlugs: ["executive-office-chair-range", "custom-storage-and-cabinetry"],
    displayOrder: 4,
    status: "published",
    seoTitle: "Office Tables and Work Desks | Destino Furniture Studio",
    seoDescription:
      "Request quotations for office tables, work desks and meeting tables from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "cafeteria-table-and-seating-range",
    name: "Cafeteria Table and Seating Range",
    categorySlug: "cafeteria-furniture",
    brandSlug: "paradise",
    furnitureType: "Cafeteria Furniture",
    image: imageAsset("products/cafeteria-table-and-seating-range/cover.jpeg"),
    gallery: [
      imageAsset("products/cafeteria-table-and-seating-range/cover.jpeg"),
      imageAsset("products/cafeteria-table-and-seating-range/gallery-02.jpeg"),
    ],
    shortDescription:
      "Cafeteria furniture for office cafes, institutional canteens and break-out areas.",
    fullDescription:
      "Cafeteria selections are planned around seating density, cleaning, circulation and usage intensity. Product-specific materials and finishes are confirmed before quotation.",
    features: [
      "Tables and seating for shared dining spaces",
      "Configuration guidance by capacity and layout",
      "Useful for institutions, factories and office cafes",
    ],
    relatedSlugs: ["restaurant-seating-and-table-range", "institutional-furniture-range"],
    featured: true,
    displayOrder: 5,
    status: "published",
    seoTitle: "Cafeteria Furniture | Destino Furniture Studio",
    seoDescription:
      "Explore cafeteria tables and chairs for commercial and institutional spaces with Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "restaurant-seating-and-table-range",
    name: "Restaurant Seating and Table Range",
    categorySlug: "restaurant-furniture",
    brandSlug: "paradise",
    furnitureType: "Restaurant Furniture",
    image: imageAsset("products/restaurant-seating-and-table-range/cover.jpeg"),
    gallery: [
      imageAsset("products/restaurant-seating-and-table-range/cover.jpeg"),
      imageAsset("products/restaurant-seating-and-table-range/gallery-02.jpeg"),
    ],
    shortDescription:
      "Furniture options for cafes, restaurants and quick-service food spaces.",
    fullDescription:
      "Restaurant furniture is selected around service style, table turnover, durability and the visual direction of the space. Confirmed specifications are added after model selection.",
    features: [
      "Dining chairs, cafe tables and break-out seating",
      "Planning support for circulation and capacity",
      "Finish coordination for hospitality interiors",
    ],
    relatedSlugs: ["cafeteria-table-and-seating-range", "lounge-and-visitor-seating"],
    displayOrder: 6,
    status: "published",
    seoTitle: "Restaurant Furniture Supplier | Destino Furniture Studio",
    seoDescription:
      "Request restaurant furniture quotations for dining chairs, cafe tables and commercial hospitality spaces.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "institutional-furniture-range",
    name: "Institutional Furniture Range",
    categorySlug: "institutional-furniture",
    furnitureType: "Institutional Furniture",
    image: imageAsset("products/institutional-furniture-range/cover.jpeg"),
    gallery: [
      imageAsset("products/institutional-furniture-range/cover.jpeg"),
      imageAsset("products/institutional-furniture-range/gallery-02.jpeg"),
    ],
    shortDescription:
      "Furniture planning and supply support for institutions, training spaces and public offices.",
    fullDescription:
      "Institutional furniture requirements are handled through enquiry and quotation so seat counts, room types, finishes and delivery scope can be confirmed accurately.",
    features: [
      "Useful for education and administrative spaces",
      "Supports bulk enquiry and project quotation",
      "Furniture categories selected by room function",
    ],
    relatedSlugs: ["training-room-furniture", "office-desk-and-table-range"],
    displayOrder: 7,
    status: "published",
    seoTitle: "Institutional Furniture | Destino Furniture Studio",
    seoDescription:
      "Plan institutional furniture for colleges, offices and public spaces through Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "custom-storage-and-cabinetry",
    name: "Custom Storage and Cabinetry",
    categorySlug: "customized-furniture",
    brandSlug: "spacewood",
    furnitureType: "Customized Furniture",
    image: imageAsset("products/custom-storage-and-cabinetry/cover.jpeg"),
    gallery: [
      imageAsset("products/custom-storage-and-cabinetry/cover.jpeg"),
      imageAsset("products/custom-storage-and-cabinetry/gallery-02.jpeg"),
    ],
    shortDescription:
      "Made-to-fit storage, cabinetry and finish-matched furniture for commercial rooms.",
    fullDescription:
      "Custom storage is scoped only after measurements, usage notes and finish preferences are reviewed. Drawings, dimensions and materials should be added in the admin panel once confirmed.",
    features: [
      "Measurement-led custom furniture workflow",
      "Finish coordination with desks and seating",
      "Admin-ready fields for drawings and brochures",
    ],
    relatedSlugs: ["office-desk-and-table-range", "office-interior-turnkey-furniture"],
    featured: true,
    displayOrder: 8,
    status: "published",
    seoTitle: "Customized Office Furniture | Destino Furniture Studio",
    seoDescription:
      "Request customized office furniture, cabinetry and storage quotations from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "office-interior-turnkey-furniture",
    name: "Office Interior Turnkey Furniture",
    categorySlug: "office-interiors",
    furnitureType: "Office Interiors",
    image: imageAsset("products/office-interior-turnkey-furniture/cover.jpeg"),
    gallery: [
      imageAsset("products/office-interior-turnkey-furniture/cover.jpeg"),
      imageAsset("products/office-interior-turnkey-furniture/gallery-02.jpeg"),
      imageAsset("products/office-interior-turnkey-furniture/gallery-03.jpeg"),
    ],
    shortDescription:
      "Furniture-led office interior support for cabins, reception spaces and work areas.",
    fullDescription:
      "Destino can support office-interior enquiries through furniture selection, finish coordination and project quotation. Site-specific scope is confirmed before any commitment is published.",
    features: [
      "Furniture-led office-interior consultation",
      "Relevant for cabins, workspaces and receptions",
      "Project-specific quotation and WhatsApp enquiry support",
    ],
    relatedSlugs: ["workstation-table-system", "custom-storage-and-cabinetry"],
    featured: true,
    displayOrder: 9,
    status: "published",
    seoTitle: "Office Interior Furniture | Destino Furniture Studio",
    seoDescription:
      "Explore office interior and furniture planning for commercial spaces in Visakhapatnam, Kakinada and Bengaluru.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "training-room-furniture",
    name: "Training Room Furniture",
    categorySlug: "institutional-furniture",
    furnitureType: "Tables and Chairs",
    image: imageAsset("products/training-room-furniture/cover.jpeg"),
    gallery: [
      imageAsset("products/training-room-furniture/cover.jpeg"),
      imageAsset("products/training-room-furniture/gallery-02.jpeg"),
    ],
    shortDescription:
      "Furniture options for institutes, classrooms, training rooms and coaching spaces.",
    fullDescription:
      "Training-room furniture is planned around capacity, storage, circulation and teaching format. Product details are confirmed after the buyer selects a model or custom scope.",
    features: [
      "Useful for coaching and training environments",
      "Supports multi-item quotation requests",
      "Furniture selection by seating capacity and room use",
    ],
    relatedSlugs: ["institutional-furniture-range", "ergonomic-task-chair-range"],
    displayOrder: 10,
    status: "published",
    seoTitle: "Training Room Furniture | Destino Furniture Studio",
    seoDescription:
      "Request training room furniture quotations for institutes, offices and learning spaces.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "lounge-and-visitor-seating",
    name: "Lounge and Visitor Seating",
    categorySlug: "office-chairs",
    furnitureType: "Soft Seating",
    image: imageAsset("products/lounge-and-visitor-seating/cover.jpeg"),
    gallery: [
      imageAsset("products/lounge-and-visitor-seating/cover.jpeg"),
      imageAsset("products/lounge-and-visitor-seating/gallery-02.jpeg"),
    ],
    shortDescription:
      "Visitor chairs and lounge seating for reception areas, cabins and waiting spaces.",
    fullDescription:
      "Visitor and lounge seating selections are coordinated with the room's use, finish palette and expected traffic. Exact upholstery and dimensions are confirmed by model.",
    features: [
      "Reception and waiting-area applications",
      "Finish coordination with surrounding furniture",
      "Useful for offices, clinics and hospitality spaces",
    ],
    relatedSlugs: ["executive-office-chair-range", "restaurant-seating-and-table-range"],
    displayOrder: 11,
    status: "published",
    seoTitle: "Visitor and Lounge Seating | Destino Furniture Studio",
    seoDescription:
      "Explore visitor chairs and lounge seating for offices, clinics and commercial interiors.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "domestic-custom-furniture-range",
    name: "Domestic Custom Furniture Range",
    categorySlug: "domestic-furniture",
    furnitureType: "Domestic Furniture",
    image: imageAsset("products/domestic-custom-furniture-range/cover.jpeg"),
    gallery: [
      imageAsset("products/domestic-custom-furniture-range/cover.jpeg"),
      imageAsset("products/domestic-custom-furniture-range/gallery-02.jpeg"),
    ],
    shortDescription:
      "Residential furniture enquiries for compact, finish-matched and custom requirements.",
    fullDescription:
      "Domestic furniture enquiries are treated as consultation-led requests, with dimensions, finishes and materials confirmed after product or custom scope review.",
    features: [
      "Custom and ready-range enquiry support",
      "Finish coordination for residential settings",
      "Quote-first workflow with no checkout or fake pricing",
    ],
    relatedSlugs: ["custom-storage-and-cabinetry", "lounge-and-visitor-seating"],
    displayOrder: 12,
    status: "published",
    seoTitle: "Domestic Furniture | Destino Furniture Studio",
    seoDescription:
      "Request residential and custom domestic furniture quotations from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
];

export const clients: Client[] = [
  { slug: "apl", name: "APL", logo: imageAsset("clients/apl.jpeg"), sector: "Corporate", displayOrder: 1 },
  { slug: "ekam", name: "Ekam", logo: imageAsset("clients/ekam.jpeg"), sector: "Corporate", displayOrder: 2 },
  { slug: "lotus-hospitals", name: "Lotus Hospitals", logo: imageAsset("clients/lotus-hospitals.jpeg"), sector: "Healthcare", displayOrder: 3 },
  { slug: "medcy", name: "Medcy", sector: "Healthcare", displayOrder: 4 },
  { slug: "indian-navy", name: "Indian Navy", logo: imageAsset("clients/indian-navy.jpeg"), sector: "Government", displayOrder: 5 },
  { slug: "ntcpwc", name: "NTCPWC", logo: imageAsset("clients/ntcpwc.jpeg"), sector: "Institutional", displayOrder: 6 },
  { slug: "tata-motors", name: "Tata Motors", logo: imageAsset("clients/tata-motors.jpeg"), sector: "Automotive", displayOrder: 7 },
  { slug: "tea-day", name: "Tea Day", logo: imageAsset("clients/tea-day.jpeg"), sector: "Hospitality", displayOrder: 8 },
  { slug: "tenet", name: "Tenet", logo: imageAsset("clients/tenet.png"), sector: "Corporate", displayOrder: 9 },
  { slug: "trinity-hospitals", name: "Trinity Hospitals", logo: imageAsset("clients/trinity-hospitals.jpeg"), sector: "Healthcare", displayOrder: 10 },
  { slug: "gite-college", name: "GITE College", logo: imageAsset("clients/gite-college.png"), sector: "Education", displayOrder: 11 },
  { slug: "government-of-ap", name: "Government of AP", logo: imageAsset("clients/government-of-ap.png"), sector: "Government", displayOrder: 12 },
  { slug: "inox", name: "INOX", logo: imageAsset("clients/inox.jpg"), sector: "Entertainment", displayOrder: 13 },
  { slug: "rak", name: "RAK", logo: imageAsset("clients/rak.png"), sector: "Corporate", displayOrder: 14 },
  { slug: "reliance-industries", name: "Reliance Industries Limited", logo: imageAsset("clients/reliance-industries.jpg"), sector: "Corporate", displayOrder: 15 },
  { slug: "shilparamam", name: "Shilparamam", logo: imageAsset("clients/shilparamam.png"), sector: "Public venue", displayOrder: 16 },
];

export const projects: Project[] = [
  {
    slug: "aadhaar-centre-turnkey-project",
    title: "Aadhaar Centre - Turnkey Project",
    clientName: "Aadhaar Centre",
    sector: "Public service",
    location: "Kakinada",
    coverImage: imageAsset("projects/aadhaar-centre-turnkey-project/cover.jpeg"),
    gallery: [
      imageAsset("projects/aadhaar-centre-turnkey-project/cover.jpeg"),
      imageAsset("projects/aadhaar-centre-turnkey-project/gallery-02.jpeg"),
      imageAsset("projects/aadhaar-centre-turnkey-project/gallery-03.jpeg"),
      imageAsset("projects/aadhaar-centre-turnkey-project/gallery-04.jpeg"),
      imageAsset("projects/aadhaar-centre-turnkey-project/gallery-05.jpeg"),
      imageAsset("projects/aadhaar-centre-turnkey-project/gallery-06.jpeg"),
    ],
    description:
      "A documented Kakinada project from the existing Destino gallery, presented as a case-study page without adding unverified dates or claims.",
    scope: ["Turnkey furniture coordination", "Work tables", "Task seating"],
    categories: ["office-interiors", "office-furniture"],
    relatedProductSlugs: ["workstation-table-system", "office-interior-turnkey-furniture"],
    featured: true,
    displayOrder: 1,
    seoTitle: "Aadhaar Centre Kakinada Project | Destino Furniture Studio",
    seoDescription: "View the Aadhaar Centre Kakinada furniture project by Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "calvin-klein-bengaluru",
    title: "Calvin Klein",
    clientName: "Calvin Klein",
    sector: "Retail",
    location: "Bengaluru",
    coverImage: imageAsset("projects/calvin-klein-bengaluru/cover.jpeg"),
    gallery: [imageAsset("projects/calvin-klein-bengaluru/cover.jpeg")],
    description:
      "A Bengaluru project record preserved from Destino's existing project gallery for enquiry and internal reference.",
    scope: ["Commercial furniture supply", "Seating coordination"],
    categories: ["office-chairs", "office-furniture"],
    relatedProductSlugs: ["executive-office-chair-range"],
    displayOrder: 2,
    seoTitle: "Calvin Klein Bengaluru Project | Destino Furniture Studio",
    seoDescription: "View the Calvin Klein Bengaluru project record from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "collector-camp-office",
    title: "Collector Camp Office",
    clientName: "Collector Camp Office",
    sector: "Government",
    location: "Rajahmundry",
    coverImage: imageAsset("projects/collector-camp-office/cover.jpeg"),
    gallery: [
      imageAsset("projects/collector-camp-office/cover.jpeg"),
      imageAsset("projects/collector-camp-office/gallery-02.jpeg"),
      imageAsset("projects/collector-camp-office/gallery-03.jpeg"),
      imageAsset("projects/collector-camp-office/gallery-04.jpeg"),
      imageAsset("projects/collector-camp-office/gallery-05.jpeg"),
      imageAsset("projects/collector-camp-office/gallery-06.jpeg"),
      imageAsset("projects/collector-camp-office/gallery-07.jpeg"),
      imageAsset("projects/collector-camp-office/gallery-08.jpeg"),
    ],
    description:
      "A government office furniture project retained from the existing Destino gallery with visible project photography.",
    scope: ["Office furniture", "Cabin furniture", "Visitor seating"],
    categories: ["office-furniture", "office-tables", "office-chairs"],
    relatedProductSlugs: ["office-desk-and-table-range", "executive-office-chair-range"],
    featured: true,
    displayOrder: 3,
    seoTitle: "Collector Camp Office Project | Destino Furniture Studio",
    seoDescription: "Explore Destino Furniture Studio's Collector Camp Office project gallery.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "credai-kakinada",
    title: "CREDAI",
    clientName: "CREDAI",
    sector: "Association",
    location: "Kakinada",
    coverImage: imageAsset("projects/credai-kakinada/cover.jpeg"),
    gallery: [
      imageAsset("projects/credai-kakinada/cover.jpeg"),
      imageAsset("projects/credai-kakinada/gallery-02.jpeg"),
      imageAsset("projects/credai-kakinada/gallery-03.jpeg"),
      imageAsset("projects/credai-kakinada/gallery-04.jpeg"),
      imageAsset("projects/credai-kakinada/gallery-05.jpeg"),
    ],
    description:
      "A Kakinada commercial project record preserved from the legacy portfolio and linked to office furniture enquiries.",
    scope: ["Office seating", "Tables", "Furniture coordination"],
    categories: ["office-furniture", "office-chairs"],
    relatedProductSlugs: ["executive-office-chair-range", "office-desk-and-table-range"],
    displayOrder: 4,
    seoTitle: "CREDAI Kakinada Project | Destino Furniture Studio",
    seoDescription: "View CREDAI Kakinada project photographs from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "falcon-chase-visakhapatnam",
    title: "Falcon Chase",
    clientName: "Falcon Chase",
    sector: "Commercial",
    location: "Visakhapatnam",
    coverVideo: imageAsset("projects/falcon-chase-visakhapatnam/cover-video.mp4"),
    gallery: [],
    description:
      "A Visakhapatnam project media entry retained from the existing Destino portfolio.",
    scope: ["Commercial furniture project"],
    categories: ["office-furniture"],
    relatedProductSlugs: ["office-interior-turnkey-furniture"],
    displayOrder: 5,
    seoTitle: "Falcon Chase Visakhapatnam Project | Destino Furniture Studio",
    seoDescription: "View the Falcon Chase Visakhapatnam project record from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "gk-tiffins-visakhapatnam",
    title: "GK Tiffins",
    clientName: "GK Tiffins",
    sector: "Hospitality",
    location: "Murali Nagar, Visakhapatnam",
    coverImage: imageAsset("projects/gk-tiffins-visakhapatnam/cover.jpeg"),
    gallery: [
      imageAsset("projects/gk-tiffins-visakhapatnam/cover.jpeg"),
      imageAsset("projects/gk-tiffins-visakhapatnam/gallery-02.jpeg"),
      imageAsset("projects/gk-tiffins-visakhapatnam/gallery-03.jpeg"),
      imageAsset("projects/gk-tiffins-visakhapatnam/gallery-04.jpeg"),
      imageAsset("projects/gk-tiffins-visakhapatnam/gallery-05.jpeg"),
    ],
    description:
      "Hospitality furniture photography from Destino's existing project collection, useful for restaurant and cafeteria enquiries.",
    scope: ["Restaurant seating", "Dining tables", "Hospitality furniture"],
    categories: ["restaurant-furniture", "cafeteria-furniture"],
    relatedProductSlugs: ["restaurant-seating-and-table-range", "cafeteria-table-and-seating-range"],
    featured: true,
    displayOrder: 6,
    seoTitle: "GK Tiffins Visakhapatnam Project | Destino Furniture Studio",
    seoDescription: "Explore GK Tiffins restaurant furniture work by Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "hallmark-solutions-kakinada",
    title: "Hallmark Solutions",
    clientName: "Hallmark Solutions",
    sector: "Corporate",
    location: "Kakinada Branch",
    coverImage: imageAsset("projects/hallmark-solutions-kakinada/cover.jpeg"),
    gallery: [
      imageAsset("projects/hallmark-solutions-kakinada/cover.jpeg"),
      imageAsset("projects/hallmark-solutions-kakinada/gallery-02.jpeg"),
      imageAsset("projects/hallmark-solutions-kakinada/gallery-03.jpeg"),
      imageAsset("projects/hallmark-solutions-kakinada/gallery-04.jpeg"),
      imageAsset("projects/hallmark-solutions-kakinada/gallery-05.jpeg"),
    ],
    description:
      "A Kakinada branch project from Destino's existing portfolio with office furniture and workstation relevance.",
    scope: ["Office furniture", "Workstation support", "Seating"],
    categories: ["office-furniture", "workstation-tables-and-chairs"],
    relatedProductSlugs: ["workstation-table-system", "ergonomic-task-chair-range"],
    displayOrder: 7,
    seoTitle: "Hallmark Solutions Kakinada Project | Destino Furniture Studio",
    seoDescription: "View Hallmark Solutions Kakinada project photographs from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "itc-cafeteria-furniture",
    title: "ITC - Cafeteria Furniture",
    clientName: "ITC",
    sector: "Cafeteria",
    location: "Bhadrachalam",
    coverImage: imageAsset("projects/itc-cafeteria-furniture/cover.jpeg"),
    gallery: [
      imageAsset("projects/itc-cafeteria-furniture/cover.jpeg"),
      imageAsset("projects/itc-cafeteria-furniture/gallery-02.jpeg"),
      imageAsset("projects/itc-cafeteria-furniture/gallery-03.jpeg"),
    ],
    description:
      "Cafeteria furniture project imagery from Destino's legacy portfolio, retained for genuine commercial furniture context.",
    scope: ["Cafeteria tables", "Cafeteria seating"],
    categories: ["cafeteria-furniture", "restaurant-furniture"],
    relatedProductSlugs: ["cafeteria-table-and-seating-range"],
    featured: true,
    displayOrder: 8,
    seoTitle: "ITC Cafeteria Furniture Project | Destino Furniture Studio",
    seoDescription: "View ITC cafeteria furniture project imagery from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "kakinada-collectorate",
    title: "Kakinada Collectorate",
    clientName: "Kakinada Collectorate",
    sector: "Government",
    location: "Kakinada",
    coverImage: imageAsset("projects/kakinada-collectorate/cover.jpeg"),
    gallery: [
      imageAsset("projects/kakinada-collectorate/cover.jpeg"),
      imageAsset("projects/kakinada-collectorate/gallery-02.jpeg"),
      imageAsset("projects/kakinada-collectorate/gallery-03.jpeg"),
    ],
    description:
      "Government office furniture work from the existing Destino project gallery.",
    scope: ["Office tables", "Seating", "Furniture supply"],
    categories: ["office-furniture", "institutional-furniture"],
    relatedProductSlugs: ["institutional-furniture-range", "office-desk-and-table-range"],
    displayOrder: 9,
    seoTitle: "Kakinada Collectorate Project | Destino Furniture Studio",
    seoDescription: "View Kakinada Collectorate project photographs from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "medcy-hospital-visakhapatnam",
    title: "Medcy Hospital",
    clientName: "Medcy Hospital",
    sector: "Healthcare",
    location: "Visakhapatnam",
    coverImage: imageAsset("projects/medcy-hospital-visakhapatnam/cover.jpeg"),
    gallery: [
      imageAsset("projects/medcy-hospital-visakhapatnam/cover.jpeg"),
      imageAsset("projects/medcy-hospital-visakhapatnam/gallery-02.jpeg"),
      imageAsset("projects/medcy-hospital-visakhapatnam/gallery-03.jpeg"),
      imageAsset("projects/medcy-hospital-visakhapatnam/gallery-04.jpeg"),
      imageAsset("projects/medcy-hospital-visakhapatnam/gallery-05.jpeg"),
    ],
    description:
      "Healthcare furniture project imagery retained from Destino's existing portfolio.",
    scope: ["Healthcare furniture", "Visitor seating", "Office furniture"],
    categories: ["office-chairs", "institutional-furniture"],
    relatedProductSlugs: ["lounge-and-visitor-seating", "institutional-furniture-range"],
    displayOrder: 10,
    seoTitle: "Medcy Hospital Visakhapatnam Project | Destino Furniture Studio",
    seoDescription: "View Medcy Hospital Visakhapatnam furniture project imagery from Destino.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "niv-solutions-guntur",
    title: "NIV Solutions",
    clientName: "NIV Solutions",
    sector: "Corporate",
    location: "Guntur",
    coverImage: imageAsset("projects/niv-solutions-guntur/cover.jpeg"),
    gallery: [
      imageAsset("projects/niv-solutions-guntur/cover.jpeg"),
      imageAsset("projects/niv-solutions-guntur/gallery-02.jpeg"),
      imageAsset("projects/niv-solutions-guntur/gallery-03.jpeg"),
      imageAsset("projects/niv-solutions-guntur/gallery-04.jpeg"),
      imageAsset("projects/niv-solutions-guntur/gallery-05.jpeg"),
      imageAsset("projects/niv-solutions-guntur/gallery-06.jpeg"),
    ],
    description:
      "Corporate project imagery from Destino's existing portfolio, connected to office and workstation enquiries.",
    scope: ["Office furniture", "Workstation furniture", "Task seating"],
    categories: ["office-furniture", "workstation-tables-and-chairs"],
    relatedProductSlugs: ["workstation-table-system", "ergonomic-task-chair-range"],
    displayOrder: 11,
    seoTitle: "NIV Solutions Guntur Project | Destino Furniture Studio",
    seoDescription: "Explore NIV Solutions project imagery from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "pace-institute-visakhapatnam",
    title: "Pace Institute",
    clientName: "Pace Institute",
    sector: "Education",
    location: "Visakhapatnam",
    coverImage: imageAsset("projects/pace-institute-visakhapatnam/cover.jpeg"),
    gallery: [
      imageAsset("projects/pace-institute-visakhapatnam/cover.jpeg"),
      imageAsset("projects/pace-institute-visakhapatnam/gallery-02.jpeg"),
      imageAsset("projects/pace-institute-visakhapatnam/gallery-03.jpeg"),
      imageAsset("projects/pace-institute-visakhapatnam/gallery-04.jpeg"),
      imageAsset("projects/pace-institute-visakhapatnam/gallery-05.jpeg"),
      imageAsset("projects/pace-institute-visakhapatnam/gallery-06.jpeg"),
    ],
    description:
      "Education-sector furniture imagery from Destino's existing project gallery.",
    scope: ["Training furniture", "Institutional seating", "Tables"],
    categories: ["institutional-furniture", "office-tables"],
    relatedProductSlugs: ["training-room-furniture", "institutional-furniture-range"],
    displayOrder: 12,
    seoTitle: "Pace Institute Visakhapatnam Project | Destino Furniture Studio",
    seoDescription: "View Pace Institute furniture project imagery from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "pastry-chef-corporate-office",
    title: "Pastry Chef Corporate Office",
    clientName: "Pastry Chef",
    sector: "Corporate office",
    location: "Vizag",
    coverImage: imageAsset("projects/pastry-chef-corporate-office/cover.jpeg"),
    gallery: [
      imageAsset("projects/pastry-chef-corporate-office/cover.jpeg"),
      imageAsset("projects/pastry-chef-corporate-office/gallery-02.jpeg"),
      imageAsset("projects/pastry-chef-corporate-office/gallery-03.jpeg"),
      imageAsset("projects/pastry-chef-corporate-office/gallery-04.jpeg"),
      imageAsset("projects/pastry-chef-corporate-office/gallery-05.jpeg"),
      imageAsset("projects/pastry-chef-corporate-office/gallery-06.jpeg"),
      imageAsset("projects/pastry-chef-corporate-office/gallery-07.jpeg"),
      imageAsset("projects/pastry-chef-corporate-office/gallery-08.jpeg"),
    ],
    description:
      "A corporate office project with visible lounge, cabin and custom furniture work, used as the primary premium visual anchor for the new website.",
    scope: ["Office interiors", "Lounge seating", "Custom furniture", "Cabin furniture"],
    categories: ["office-interiors", "customized-furniture", "office-chairs"],
    relatedProductSlugs: ["office-interior-turnkey-furniture", "custom-storage-and-cabinetry"],
    featured: true,
    displayOrder: 13,
    seoTitle: "Pastry Chef Corporate Office Project | Destino Furniture Studio",
    seoDescription: "View the Pastry Chef corporate office furniture project by Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "spl-logistics-turnkey-project",
    title: "SPL Logistics - Turnkey Project",
    clientName: "SPL Logistics",
    sector: "Logistics",
    location: "Visakhapatnam",
    coverImage: imageAsset("projects/spl-logistics-turnkey-project/cover.jpeg"),
    gallery: [
      imageAsset("projects/spl-logistics-turnkey-project/cover.jpeg"),
      imageAsset("projects/spl-logistics-turnkey-project/gallery-02.jpeg"),
      imageAsset("projects/spl-logistics-turnkey-project/gallery-03.jpeg"),
      imageAsset("projects/spl-logistics-turnkey-project/gallery-04.jpeg"),
      imageAsset("projects/spl-logistics-turnkey-project/gallery-05.jpeg"),
      imageAsset("projects/spl-logistics-turnkey-project/gallery-06.jpeg"),
      imageAsset("projects/spl-logistics-turnkey-project/gallery-07.jpeg"),
      imageAsset("projects/spl-logistics-turnkey-project/gallery-08.jpeg"),
    ],
    description:
      "A Visakhapatnam turnkey office project from Destino's existing gallery, with workstation and seating relevance.",
    scope: ["Workstation furniture", "Task seating", "Turnkey furniture coordination"],
    categories: ["workstation-tables-and-chairs", "office-interiors"],
    relatedProductSlugs: ["workstation-table-system", "office-interior-turnkey-furniture"],
    featured: true,
    displayOrder: 14,
    seoTitle: "SPL Logistics Visakhapatnam Project | Destino Furniture Studio",
    seoDescription: "Explore SPL Logistics turnkey project imagery from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "sub-collectorate-amalapuram",
    title: "Sub-Collectorate",
    clientName: "Sub-Collectorate",
    sector: "Government",
    location: "Amalapuram",
    coverImage: imageAsset("projects/sub-collectorate-amalapuram/cover.jpeg"),
    gallery: [
      imageAsset("projects/sub-collectorate-amalapuram/cover.jpeg"),
      imageAsset("projects/sub-collectorate-amalapuram/gallery-02.jpeg"),
      imageAsset("projects/sub-collectorate-amalapuram/gallery-03.jpeg"),
      imageAsset("projects/sub-collectorate-amalapuram/gallery-04.jpeg"),
    ],
    description:
      "A government project record retained from the existing Destino portfolio.",
    scope: ["Office tables", "Seating", "Institutional furniture"],
    categories: ["institutional-furniture", "office-furniture"],
    relatedProductSlugs: ["institutional-furniture-range", "office-desk-and-table-range"],
    displayOrder: 15,
    seoTitle: "Sub-Collectorate Amalapuram Project | Destino Furniture Studio",
    seoDescription: "View Sub-Collectorate Amalapuram project imagery from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "tarnika-corporate-office-turnkey-project",
    title: "Tarnika Corporate Office - Turnkey Project",
    clientName: "Tarnika",
    sector: "Corporate office",
    location: "Bengaluru",
    coverImage: imageAsset("projects/tarnika-corporate-office-turnkey-project/cover.jpeg"),
    gallery: [
      imageAsset("projects/tarnika-corporate-office-turnkey-project/cover.jpeg"),
      imageAsset("projects/tarnika-corporate-office-turnkey-project/gallery-02.jpeg"),
      imageAsset("projects/tarnika-corporate-office-turnkey-project/gallery-03.jpeg"),
      imageAsset("projects/tarnika-corporate-office-turnkey-project/gallery-04.jpeg"),
      imageAsset("projects/tarnika-corporate-office-turnkey-project/gallery-05.jpeg"),
      imageAsset("projects/tarnika-corporate-office-turnkey-project/gallery-06.jpeg"),
      imageAsset("projects/tarnika-corporate-office-turnkey-project/gallery-07.jpeg"),
      imageAsset("projects/tarnika-corporate-office-turnkey-project/gallery-08.jpeg"),
    ],
    description:
      "A Bengaluru corporate office project retained from Destino's existing portfolio.",
    scope: ["Turnkey furniture coordination", "Office interiors", "Workstations"],
    categories: ["office-interiors", "workstation-tables-and-chairs"],
    relatedProductSlugs: ["office-interior-turnkey-furniture", "workstation-table-system"],
    featured: true,
    displayOrder: 16,
    seoTitle: "Tarnika Bengaluru Corporate Office Project | Destino Furniture Studio",
    seoDescription: "View Tarnika corporate office project imagery from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "time-institute-visakhapatnam",
    title: "Time Institute",
    clientName: "Time Institute",
    sector: "Education",
    location: "Dwarakanagar, Visakhapatnam",
    coverImage: imageAsset("projects/time-institute-visakhapatnam/cover.jpeg"),
    gallery: [
      imageAsset("projects/time-institute-visakhapatnam/cover.jpeg"),
      imageAsset("projects/time-institute-visakhapatnam/gallery-02.jpeg"),
      imageAsset("projects/time-institute-visakhapatnam/gallery-03.jpeg"),
      imageAsset("projects/time-institute-visakhapatnam/gallery-04.jpeg"),
    ],
    description:
      "Education and training-space furniture imagery from Destino's existing portfolio.",
    scope: ["Training room furniture", "Tables", "Seating"],
    categories: ["institutional-furniture", "office-tables"],
    relatedProductSlugs: ["training-room-furniture", "institutional-furniture-range"],
    displayOrder: 17,
    seoTitle: "Time Institute Visakhapatnam Project | Destino Furniture Studio",
    seoDescription: "View Time Institute Visakhapatnam furniture project imagery from Destino Furniture Studio.",
    updatedAt: "2026-08-26",
  },
];

export const locations: Location[] = [
  {
    slug: "visakhapatnam",
    name: "Visakhapatnam",
    region: "Andhra Pradesh",
    intro:
      "Destino supports office furniture, ergonomic chairs, workstation tables, custom furniture and commercial-interior enquiries for Visakhapatnam buyers.",
    services: [
      "Office furniture in Visakhapatnam",
      "Ergonomic chairs and office seating",
      "Office tables and workstation planning",
      "Restaurant and cafeteria furniture",
      "Custom furniture consultation",
    ],
    serviceAreas: ["Commercial offices", "Institutions", "Healthcare spaces", "Hospitality projects"],
    relatedProjectSlugs: [
      "pastry-chef-corporate-office",
      "spl-logistics-turnkey-project",
      "gk-tiffins-visakhapatnam",
      "time-institute-visakhapatnam",
    ],
    seoTitle: "Office Furniture in Visakhapatnam | Destino Furniture Studio",
    seoDescription:
      "Contact Destino Furniture Studio for office furniture, ergonomic chairs, workstations and custom furniture in Visakhapatnam.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "kakinada",
    name: "Kakinada",
    region: "Andhra Pradesh",
    intro:
      "Destino works with Kakinada businesses and institutions on office furniture, project furniture, workstation systems and custom requirements.",
    services: [
      "Office furniture in Kakinada",
      "Workstation tables and chairs",
      "Institutional furniture",
      "Commercial furniture quotation",
      "Furniture for branch-office projects",
    ],
    serviceAreas: ["Corporate offices", "Public-service offices", "Education spaces", "Commercial branches"],
    relatedProjectSlugs: [
      "aadhaar-centre-turnkey-project",
      "credai-kakinada",
      "hallmark-solutions-kakinada",
      "kakinada-collectorate",
    ],
    seoTitle: "Office Furniture in Kakinada | Destino Furniture Studio",
    seoDescription:
      "Request office furniture, institutional furniture and workstation quotations from Destino Furniture Studio in Kakinada.",
    updatedAt: "2026-08-26",
  },
  {
    slug: "bengaluru",
    name: "Bengaluru",
    region: "Karnataka",
    intro:
      "Destino handles Bengaluru furniture enquiries for offices, retail and commercial project requirements through consultation-led quotations.",
    services: [
      "Office furniture in Bengaluru",
      "Executive chairs and task seating",
      "Office-interior furniture coordination",
      "Custom furniture quotation",
      "Commercial project furniture",
    ],
    serviceAreas: ["Corporate offices", "Retail spaces", "Commercial interiors", "Project enquiries"],
    relatedProjectSlugs: ["tarnika-corporate-office-turnkey-project", "calvin-klein-bengaluru"],
    seoTitle: "Office Furniture in Bengaluru | Destino Furniture Studio",
    seoDescription:
      "Contact Destino Furniture Studio for office furniture, ergonomic chairs and custom furniture enquiries in Bengaluru.",
    updatedAt: "2026-08-26",
  },
];

export const faqs: Faq[] = [
  {
    question: "Can I request a quote without creating an account?",
    answer:
      "Yes. Customers can save products to the wishlist on their device and request a combined quotation without registration.",
  },
  {
    question: "Are prices shown on the website?",
    answer:
      "No. Pricing is not displayed until product model, quantities, finishes and delivery scope are confirmed.",
  },
  {
    question: "Can Destino help with office interiors and custom furniture?",
    answer:
      "Yes. Destino handles office-interior, workstation, customized furniture and commercial furniture enquiries through a consultation-led quotation process.",
  },
  {
    question: "Which locations does Destino serve?",
    answer:
      "Verified city locations are Visakhapatnam, Kakinada and Bengaluru. Street addresses and hours should be confirmed in the admin panel before publishing.",
  },
];
